# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchgit,
  ...
}:

linkFarm "zig-packages" [
  {
    name = "cli-0.10.0-2eKe_5kEAQBeHqKxUHNTGnETzu81rqKWwT1WPt1jXBt0";
    path = fetchgit {
      url = "https://github.com/sam701/zig-cli";
      rev = "cb44aade25a3c1eddd8b6f990b50c2189442c1e2";
      hash = "sha256-/rmfwWseEeqK7nDdSHKwOAPmdsBpFD9/1wg1uHLJ+eU=";
    };
  }
]
